export const production = {"NEXT_PUBLIC_SUPABASE_URL":"","NEXT_PUBLIC_SUPABASE_ANON_KEY":"","SUPABASE_SERVICE_ROLE_KEY":"","OPENROUTER_API_KEY":"","LEMONSQUEEZY_API_KEY":"","LEMONSQUEEZY_STORE_ID":"","LEMONSQUEEZY_WEBHOOK_SECRET":"","NEXT_PUBLIC_APP_URL":"http://localhost:3000"};
export const development = {"NEXT_PUBLIC_SUPABASE_URL":"","NEXT_PUBLIC_SUPABASE_ANON_KEY":"","SUPABASE_SERVICE_ROLE_KEY":"","OPENROUTER_API_KEY":"","LEMONSQUEEZY_API_KEY":"","LEMONSQUEEZY_STORE_ID":"","LEMONSQUEEZY_WEBHOOK_SECRET":"","NEXT_PUBLIC_APP_URL":"http://localhost:3000"};
export const test = {};
